# springfox.documentation.swagger.v2.path=/datos/api/doc
server:
  contextPath: /ubuntu-postgraduate-api
  # Configure the server to run with SSL/TLS and using HTTPS
  port: 8443
#  ssl:
#    key-store: classpath:ssl/tomcat.keystore
#    key-store-password: preving
#    key-password: preving

jwt:
  header: Authorization
  prefijo: Bearer
  secret: clave para encriptar jwt!
  expiration: 86400
  route:
    authentication:
      path: /login
      refresh: /refresh

users:
  usuariosList:
    -
      id: 1
      username: ubuntu
      password: ubuntu_team
      firstname: Ubuntu
      lastname: S.L.
      email: ubuntuafrika@preving.com
      enabled: true

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/sajp?useSSL=false
    username: root
    password: era9buh3
    driver-class-name: Com.mysql.jdbc.Driver

    # To See the database table in the console
    jpa:
      show-sql: true
      #Hibernate properties
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      # create, create-drop
      hibernate:
        ddl-auto: update
  profiles:
    active: dev

  # http://www.mkyong.com/java/how-to-enable-pretty-print-json-output-jackson/
  # opara que las respuestas json vayan indentadas
  jackson:
    serialization:
      INDENT_OUTPUT: true

  jmx:
    enabled: false  # necesario para no obtener el siguiente error:

  # Unable to register MBean [org.apache.tomcat.dbcp.dbcp2.BasicDataSource
  # Show or not log for each sql query
  #jpa:
    #show-sql: true

  # Hibernate ddl auto (create, create-drop, update): with "update" the database
  # schema will be automatically updated accordingly to java entities found in
  # the project
  #hibernate:
    #ddl-auto: create

---

spring:
  profiles: dev

datasource:
  url: jdbc:mysql://localhost:3306/sajp
  username: root
  password: kamara1734
  driver-class-name: com.mysql.jdbc.Driver
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

#   db-sajp:
#     url: jdbc:oracle:thin:@155.155.15.228:1521/pre
#     username: sajp
#     password: 6DPtc36z1111_
#     driver-class-name: oracle.jdbc.driver.OracleDriver

#   db-secure:
#     url: jdbc:oracle:thin:@155.155.15.228:1521/pre
#     username: optec
#     password: 6DPtc36z1111_
#     driver-class-name: oracle.jdbc.driver.OracleDriver

mail:
   host: mail.preving.com
   port: 25
   userName: intranet@preving.com
   password: Int..26980
---

spring:
  profiles: preprod

mail:
   host: 82.223.77.42
   port: 25
   userName: intranet@preving.com
   password: Int..26980
---

spring:
  profiles: prod

mail:
   host: mail.preving.com
   port: 25
   userName: intranet@preving.com
   password: Int..26980
